const Map<String, String> localizationZhCn = {
  'appName': 'A4 Flow',
  'home': '主页',
  'settings': '设置',
  'newDocument': '新建文档',
  'openDocument': '打开文档',
  'save': '保存',
  'export': '导出',
  'delete': '删除',
  'cancel': '取消',
  'confirm': '确认',
  'language': '语言',
  'theme': '主题',
  'darkMode': '深色模式',
  'lightMode': '浅色模式',
  'unit': '单位',
  'about': '关于',
  'termsOfService': '服务条款',
  'privacyPolicy': '隐私政策',
  'adWarning': '广告警告',
  'articleMode': '文章',
  'spreadsheetMode': '电子表格',
  'drawingMode': '绘图',
  'calculatorMode': '计算器',
  'symbolsMode': '符号',
  'latexMode': 'LaTeX',
  'documentSaved': '文档保存成功',
  'errorOccurred': '发生错误',
};
