const Map<String, String> localizationDe = {
  'appName': 'A4 Flow',
  'home': 'Startseite',
  'settings': 'Einstellungen',
  'newDocument': 'Neues Dokument',
  'openDocument': 'Dokument Öffnen',
  'save': 'Speichern',
  'export': 'Exportieren',
  'delete': 'Löschen',
  'cancel': 'Abbrechen',
  'confirm': 'Bestätigen',
  'language': 'Sprache',
  'theme': 'Design',
  'darkMode': 'Dunkler Modus',
  'lightMode': 'Heller Modus',
  'unit': 'Einheit',
  'about': 'Über',
  'termsOfService': 'Nutzungsbedingungen',
  'privacyPolicy': 'Datenschutzrichtlinie',
  'adWarning': 'Anzeigenwarnung',
  'articleMode': 'Artikel',
  'spreadsheetMode': 'Tabellenkalkulation',
  'drawingMode': 'Zeichnung',
  'calculatorMode': 'Taschenrechner',
  'symbolsMode': 'Symbole',
  'latexMode': 'LaTeX',
  'documentSaved': 'Dokument erfolgreich gespeichert',
  'errorOccurred': 'Ein Fehler ist aufgetreten',
};
