const Map<String, String> localizationFr = {
  'appName': 'A4 Flow',
  'home': 'Accueil',
  'settings': 'Paramètres',
  'newDocument': 'Nouveau Document',
  'openDocument': 'Ouvrir Document',
  'save': 'Enregistrer',
  'export': 'Exporter',
  'delete': 'Supprimer',
  'cancel': 'Annuler',
  'confirm': 'Confirmer',
  'language': 'Langue',
  'theme': 'Thème',
  'darkMode': 'Mode Sombre',
  'lightMode': 'Mode Clair',
  'unit': 'Unité',
  'about': 'À propos',
  'termsOfService': 'Conditions de Service',
  'privacyPolicy': 'Politique de Confidentialité',
  'adWarning': 'Avertissement Publicitaire',
  'articleMode': 'Article',
  'spreadsheetMode': 'Feuille de Calcul',
  'drawingMode': 'Dessin',
  'calculatorMode': 'Calculatrice',
  'symbolsMode': 'Symboles',
  'latexMode': 'LaTeX',
  'documentSaved': 'Document enregistré avec succès',
  'errorOccurred': 'Une erreur est survenue',
};
