const Map<String, String> localizationPtBr = {
  // Common
  'appName': 'A4 Flow',
  'home': 'Início',
  'settings': 'Configurações',
  'newDocument': 'Novo Documento',
  'openDocument': 'Abrir Documento',
  'save': 'Salvar',
  'export': 'Exportar',
  'delete': 'Excluir',
  'cancel': 'Cancelar',
  'confirm': 'Confirmar',
  'language': 'Idioma',
  'theme': 'Tema',
  'darkMode': 'Modo Escuro',
  'lightMode': 'Modo Claro',
  'unit': 'Unidade',
  'about': 'Sobre',
  'termsOfService': 'Termos de Serviço',
  'privacyPolicy': 'Política de Privacidade',
  'adWarning': 'Aviso sobre Publicidade',
  
  // Editor modes
  'articleMode': 'Artigo',
  'spreadsheetMode': 'Planilha',
  'drawingMode': 'Desenho',
  'calculatorMode': 'Calculadora',
  'symbolsMode': 'Símbolos',
  'latexMode': 'LaTeX',
  
  // Home screen
  'recentDocuments': 'Documentos Recentes',
  'noRecentDocuments': 'Nenhum documento recente',
  'createNewDocument': 'Criar Novo Documento',
  'openFromFile': 'Abrir do Arquivo',
  
  // Editor
  'untitled': 'Sem Título',
  'undo': 'Desfazer',
  'redo': 'Refazer',
  'cut': 'Cortar',
  'copy': 'Copiar',
  'paste': 'Colar',
  'duplicate': 'Duplicar',
  'delete': 'Excluir',
  'selectAll': 'Selecionar Tudo',
  'zoomIn': 'Aumentar Zoom',
  'zoomOut': 'Diminuir Zoom',
  'fitToScreen': 'Ajustar à Tela',
  'resetZoom': 'Resetar Zoom',
  
  // Article mode
  'title': 'Título',
  'abstract': 'Resumo',
  'section': 'Seção',
  'equation': 'Equação',
  'figure': 'Figura',
  'table': 'Tabela',
  'reference': 'Referência',
  'columns': 'Colunas',
  'margins': 'Margens',
  'spacing': 'Espaçamento',
  'font': 'Fonte',
  'fontSize': 'Tamanho da Fonte',
  'bold': 'Negrito',
  'italic': 'Itálico',
  'underline': 'Sublinhado',
  'strikethrough': 'Tachado',
  'superscript': 'Sobrescrito',
  'subscript': 'Subscrito',
  'textColor': 'Cor do Texto',
  'backgroundColor': 'Cor de Fundo',
  'alignment': 'Alinhamento',
  'alignLeft': 'Alinhar à Esquerda',
  'alignCenter': 'Centralizar',
  'alignRight': 'Alinhar à Direita',
  'alignJustify': 'Justificar',
  
  // Spreadsheet mode
  'rows': 'Linhas',
  'columns': 'Colunas',
  'addRow': 'Adicionar Linha',
  'addColumn': 'Adicionar Coluna',
  'deleteRow': 'Excluir Linha',
  'deleteColumn': 'Excluir Coluna',
  'insertFormula': 'Inserir Fórmula',
  'scientificFormulas': 'Fórmulas Científicas',
  'insertChart': 'Inserir Gráfico',
  'chartType': 'Tipo de Gráfico',
  'barChart': 'Gráfico de Barras',
  'lineChart': 'Gráfico de Linhas',
  'pieChart': 'Gráfico de Pizza',
  'scatterChart': 'Gráfico de Dispersão',
  
  // Drawing mode
  'pencil': 'Lápis',
  'pen': 'Caneta',
  'eraser': 'Borracha',
  'line': 'Linha',
  'rectangle': 'Retângulo',
  'circle': 'Círculo',
  'triangle': 'Triângulo',
  'polygon': 'Polígono',
  'text': 'Texto',
  'layers': 'Camadas',
  'strokeWidth': 'Espessura do Traço',
  'strokeColor': 'Cor do Traço',
  'fillColor': 'Cor de Preenchimento',
  'opacity': 'Opacidade',
  'snapToGrid': 'Alinhar à Grade',
  'gridSize': 'Tamanho da Grade',
  
  // Calculator mode
  'scientificCalculator': 'Calculadora Científica',
  'history': 'Histórico',
  'clear': 'Limpar',
  'sine': 'Seno',
  'cosine': 'Cosseno',
  'tangent': 'Tangente',
  'logarithm': 'Logaritmo',
  'naturalLog': 'Logaritmo Natural',
  'squareRoot': 'Raiz Quadrada',
  'power': 'Potência',
  'factorial': 'Fatorial',
  'pi': 'π',
  'e': 'e',
  'degrees': 'Graus',
  'radians': 'Radianos',
  'precision': 'Precisão',
  'insertResult': 'Inserir Resultado',
  'asText': 'Como Texto',
  'asImage': 'Como Imagem',
  'asLatex': 'Como LaTeX',
  
  // Symbols mode
  'greekLetters': 'Letras Gregas',
  'operators': 'Operadores',
  'arrows': 'Setas',
  'sets': 'Conjuntos',
  'logic': 'Lógica',
  'relations': 'Relações',
  'search': 'Pesquisar',
  'favorites': 'Favoritos',
  'symbolSize': 'Tamanho do Símbolo',
  'symbolColor': 'Cor do Símbolo',
  
  // LaTeX mode
  'latexEditor': 'Editor LaTeX',
  'preview': 'Visualização',
  'render': 'Renderizar',
  'packages': 'Pacotes',
  'commonPackages': 'Pacotes Comuns',
  'amsmath': 'amsmath',
  'amssymb': 'amssymb',
  'geometry': 'geometry',
  'graphicx': 'graphicx',
  'tikz': 'tikz',
  'previewFont': 'Fonte da Visualização',
  
  // Common features
  'insertImage': 'Inserir Imagem',
  'insertDocument': 'Inserir Documento',
  'insertTable': 'Inserir Tabela',
  'insertChart': 'Inserir Gráfico',
  'insertShape': 'Inserir Forma',
  'insertText': 'Inserir Texto',
  'resize': 'Redimensionar',
  'move': 'Mover',
  'rotate': 'Rotacionar',
  'group': 'Agrupar',
  'ungroup': 'Desagrupar',
  'bringToFront': 'Trazer para Frente',
  'sendToBack': 'Enviar para Trás',
  'align': 'Alinhar',
  'distribute': 'Distribuir',
  
  // Export
  'exportAs': 'Exportar Como',
  'exportPdf': 'Exportar como PDF',
  'exportImage': 'Exportar como Imagem',
  'exportMarkdown': 'Exportar como Markdown',
  'exportProject': 'Exportar Projeto',
  'exportSettings': 'Configurações de Exportação',
  'pageSize': 'Tamanho da Página',
  'orientation': 'Orientação',
  'portrait': 'Retrato',
  'landscape': 'Paisagem',
  'resolution': 'Resolução',
  'quality': 'Qualidade',
  
  // File operations
  'newFile': 'Novo Arquivo',
  'openFile': 'Abrir Arquivo',
  'saveFile': 'Salvar Arquivo',
  'saveAs': 'Salvar Como',
  'recentFiles': 'Arquivos Recentes',
  'noRecentFiles': 'Nenhum arquivo recente',
  'fileNotFound': 'Arquivo não encontrado',
  'errorSaving': 'Erro ao salvar arquivo',
  'errorOpening': 'Erro ao abrir arquivo',
  
  // Settings
  'generalSettings': 'Configurações Gerais',
  'editorSettings': 'Configurações do Editor',
  'exportSettings': 'Configurações de Exportação',
  'about': 'Sobre',
  'version': 'Versão',
  'appDescription': 'Editor avançado e local para artigos científicos, teses e documentos acadêmicos',
  'allLocalStorage': 'Todos os dados são armazenados localmente no seu dispositivo',
  'noCloudSync': 'Sem sincronização em nuvem',
  'noDataCollection': 'Sem coleta de dados',
  'adSupportedApp': 'Aplicativo gratuito com suporte a anúncios',
  
  // Permissions
  'storagePermission': 'Permissão de Armazenamento',
  'storagePermissionDescription': 'O aplicativo precisa de permissão para ler e escrever arquivos',
  'cameraPermission': 'Permissão de Câmera',
  'cameraPermissionDescription': 'O aplicativo precisa de permissão para usar a câmera',
  'grant': 'Conceder',
  'deny': 'Negar',
  
  // Messages
  'documentSaved': 'Documento salvo com sucesso',
  'documentDeleted': 'Documento excluído',
  'documentExported': 'Documento exportado com sucesso',
  'copyToClipboard': 'Copiado para a área de transferência',
  'errorOccurred': 'Ocorreu um erro',
  'tryAgain': 'Tentar Novamente',
  'noData': 'Nenhum dado disponível',
  'loading': 'Carregando...',
  'success': 'Sucesso',
  'error': 'Erro',
  'warning': 'Aviso',
  'info': 'Informação',
};
