const Map<String, String> localizationIt = {
  'appName': 'A4 Flow',
  'home': 'Home',
  'settings': 'Impostazioni',
  'newDocument': 'Nuovo Documento',
  'openDocument': 'Apri Documento',
  'save': 'Salva',
  'export': 'Esporta',
  'delete': 'Elimina',
  'cancel': 'Annulla',
  'confirm': 'Conferma',
  'language': 'Lingua',
  'theme': 'Tema',
  'darkMode': 'Modalità Scura',
  'lightMode': 'Modalità Chiara',
  'unit': 'Unità',
  'about': 'Informazioni',
  'termsOfService': 'Termini di Servizio',
  'privacyPolicy': 'Politica sulla Privacy',
  'adWarning': 'Avvertenza Pubblicitaria',
  'articleMode': 'Articolo',
  'spreadsheetMode': 'Foglio di Calcolo',
  'drawingMode': 'Disegno',
  'calculatorMode': 'Calcolatrice',
  'symbolsMode': 'Simboli',
  'latexMode': 'LaTeX',
  'documentSaved': 'Documento salvato con successo',
  'errorOccurred': 'Si è verificato un errore',
};
