const Map<String, String> localizationEs = {
  'appName': 'A4 Flow',
  'home': 'Inicio',
  'settings': 'Configuración',
  'newDocument': 'Nuevo Documento',
  'openDocument': 'Abrir Documento',
  'save': 'Guardar',
  'export': 'Exportar',
  'delete': 'Eliminar',
  'cancel': 'Cancelar',
  'confirm': 'Confirmar',
  'language': 'Idioma',
  'theme': 'Tema',
  'darkMode': 'Modo Oscuro',
  'lightMode': 'Modo Claro',
  'unit': 'Unidad',
  'about': 'Acerca de',
  'termsOfService': 'Términos de Servicio',
  'privacyPolicy': 'Política de Privacidad',
  'adWarning': 'Aviso de Publicidad',
  'articleMode': 'Artículo',
  'spreadsheetMode': 'Hoja de Cálculo',
  'drawingMode': 'Dibujo',
  'calculatorMode': 'Calculadora',
  'symbolsMode': 'Símbolos',
  'latexMode': 'LaTeX',
  'documentSaved': 'Documento guardado correctamente',
  'errorOccurred': 'Ocurrió un error',
};
