const Map<String, String> localizationEnUs = {
  // Common
  'appName': 'A4 Flow',
  'home': 'Home',
  'settings': 'Settings',
  'newDocument': 'New Document',
  'openDocument': 'Open Document',
  'save': 'Save',
  'export': 'Export',
  'delete': 'Delete',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'language': 'Language',
  'theme': 'Theme',
  'darkMode': 'Dark Mode',
  'lightMode': 'Light Mode',
  'unit': 'Unit',
  'about': 'About',
  'termsOfService': 'Terms of Service',
  'privacyPolicy': 'Privacy Policy',
  'adWarning': 'Ad Warning',
  
  // Editor modes
  'articleMode': 'Article',
  'spreadsheetMode': 'Spreadsheet',
  'drawingMode': 'Drawing',
  'calculatorMode': 'Calculator',
  'symbolsMode': 'Symbols',
  'latexMode': 'LaTeX',
  
  // Home screen
  'recentDocuments': 'Recent Documents',
  'noRecentDocuments': 'No recent documents',
  'createNewDocument': 'Create New Document',
  'openFromFile': 'Open from File',
  
  // Editor
  'untitled': 'Untitled',
  'undo': 'Undo',
  'redo': 'Redo',
  'cut': 'Cut',
  'copy': 'Copy',
  'paste': 'Paste',
  'duplicate': 'Duplicate',
  'delete': 'Delete',
  'selectAll': 'Select All',
  'zoomIn': 'Zoom In',
  'zoomOut': 'Zoom Out',
  'fitToScreen': 'Fit to Screen',
  'resetZoom': 'Reset Zoom',
  
  // Article mode
  'title': 'Title',
  'abstract': 'Abstract',
  'section': 'Section',
  'equation': 'Equation',
  'figure': 'Figure',
  'table': 'Table',
  'reference': 'Reference',
  'columns': 'Columns',
  'margins': 'Margins',
  'spacing': 'Spacing',
  'font': 'Font',
  'fontSize': 'Font Size',
  'bold': 'Bold',
  'italic': 'Italic',
  'underline': 'Underline',
  'strikethrough': 'Strikethrough',
  'superscript': 'Superscript',
  'subscript': 'Subscript',
  'textColor': 'Text Color',
  'backgroundColor': 'Background Color',
  'alignment': 'Alignment',
  'alignLeft': 'Align Left',
  'alignCenter': 'Center',
  'alignRight': 'Align Right',
  'alignJustify': 'Justify',
  
  // Spreadsheet mode
  'rows': 'Rows',
  'columns': 'Columns',
  'addRow': 'Add Row',
  'addColumn': 'Add Column',
  'deleteRow': 'Delete Row',
  'deleteColumn': 'Delete Column',
  'insertFormula': 'Insert Formula',
  'scientificFormulas': 'Scientific Formulas',
  'insertChart': 'Insert Chart',
  'chartType': 'Chart Type',
  'barChart': 'Bar Chart',
  'lineChart': 'Line Chart',
  'pieChart': 'Pie Chart',
  'scatterChart': 'Scatter Chart',
  
  // Drawing mode
  'pencil': 'Pencil',
  'pen': 'Pen',
  'eraser': 'Eraser',
  'line': 'Line',
  'rectangle': 'Rectangle',
  'circle': 'Circle',
  'triangle': 'Triangle',
  'polygon': 'Polygon',
  'text': 'Text',
  'layers': 'Layers',
  'strokeWidth': 'Stroke Width',
  'strokeColor': 'Stroke Color',
  'fillColor': 'Fill Color',
  'opacity': 'Opacity',
  'snapToGrid': 'Snap to Grid',
  'gridSize': 'Grid Size',
  
  // Calculator mode
  'scientificCalculator': 'Scientific Calculator',
  'history': 'History',
  'clear': 'Clear',
  'sine': 'Sine',
  'cosine': 'Cosine',
  'tangent': 'Tangent',
  'logarithm': 'Logarithm',
  'naturalLog': 'Natural Log',
  'squareRoot': 'Square Root',
  'power': 'Power',
  'factorial': 'Factorial',
  'pi': 'π',
  'e': 'e',
  'degrees': 'Degrees',
  'radians': 'Radians',
  'precision': 'Precision',
  'insertResult': 'Insert Result',
  'asText': 'As Text',
  'asImage': 'As Image',
  'asLatex': 'As LaTeX',
  
  // Symbols mode
  'greekLetters': 'Greek Letters',
  'operators': 'Operators',
  'arrows': 'Arrows',
  'sets': 'Sets',
  'logic': 'Logic',
  'relations': 'Relations',
  'search': 'Search',
  'favorites': 'Favorites',
  'symbolSize': 'Symbol Size',
  'symbolColor': 'Symbol Color',
  
  // LaTeX mode
  'latexEditor': 'LaTeX Editor',
  'preview': 'Preview',
  'render': 'Render',
  'packages': 'Packages',
  'commonPackages': 'Common Packages',
  'amsmath': 'amsmath',
  'amssymb': 'amssymb',
  'geometry': 'geometry',
  'graphicx': 'graphicx',
  'tikz': 'tikz',
  'previewFont': 'Preview Font',
  
  // Common features
  'insertImage': 'Insert Image',
  'insertDocument': 'Insert Document',
  'insertTable': 'Insert Table',
  'insertChart': 'Insert Chart',
  'insertShape': 'Insert Shape',
  'insertText': 'Insert Text',
  'resize': 'Resize',
  'move': 'Move',
  'rotate': 'Rotate',
  'group': 'Group',
  'ungroup': 'Ungroup',
  'bringToFront': 'Bring to Front',
  'sendToBack': 'Send to Back',
  'align': 'Align',
  'distribute': 'Distribute',
  
  // Export
  'exportAs': 'Export As',
  'exportPdf': 'Export as PDF',
  'exportImage': 'Export as Image',
  'exportMarkdown': 'Export as Markdown',
  'exportProject': 'Export Project',
  'exportSettings': 'Export Settings',
  'pageSize': 'Page Size',
  'orientation': 'Orientation',
  'portrait': 'Portrait',
  'landscape': 'Landscape',
  'resolution': 'Resolution',
  'quality': 'Quality',
  
  // File operations
  'newFile': 'New File',
  'openFile': 'Open File',
  'saveFile': 'Save File',
  'saveAs': 'Save As',
  'recentFiles': 'Recent Files',
  'noRecentFiles': 'No recent files',
  'fileNotFound': 'File not found',
  'errorSaving': 'Error saving file',
  'errorOpening': 'Error opening file',
  
  // Settings
  'generalSettings': 'General Settings',
  'editorSettings': 'Editor Settings',
  'exportSettings': 'Export Settings',
  'about': 'About',
  'version': 'Version',
  'appDescription': 'Advanced local editor for scientific articles, theses and academic documents',
  'allLocalStorage': 'All data is stored locally on your device',
  'noCloudSync': 'No cloud synchronization',
  'noDataCollection': 'No data collection',
  'adSupportedApp': 'Free app with ad support',
  
  // Permissions
  'storagePermission': 'Storage Permission',
  'storagePermissionDescription': 'The app needs permission to read and write files',
  'cameraPermission': 'Camera Permission',
  'cameraPermissionDescription': 'The app needs permission to use the camera',
  'grant': 'Grant',
  'deny': 'Deny',
  
  // Messages
  'documentSaved': 'Document saved successfully',
  'documentDeleted': 'Document deleted',
  'documentExported': 'Document exported successfully',
  'copyToClipboard': 'Copied to clipboard',
  'errorOccurred': 'An error occurred',
  'tryAgain': 'Try Again',
  'noData': 'No data available',
  'loading': 'Loading...',
  'success': 'Success',
  'error': 'Error',
  'warning': 'Warning',
  'info': 'Information',
};
