const Map<String, String> localizationRu = {
  'appName': 'A4 Flow',
  'home': 'Главная',
  'settings': 'Параметры',
  'newDocument': 'Новый документ',
  'openDocument': 'Открыть документ',
  'save': 'Сохранить',
  'export': 'Экспорт',
  'delete': 'Удалить',
  'cancel': 'Отмена',
  'confirm': 'Подтвердить',
  'language': 'Язык',
  'theme': 'Тема',
  'darkMode': 'Темный режим',
  'lightMode': 'Светлый режим',
  'unit': 'Единица',
  'about': 'О приложении',
  'termsOfService': 'Условия использования',
  'privacyPolicy': 'Политика конфиденциальности',
  'adWarning': 'Предупреждение об объявлениях',
  'articleMode': 'Статья',
  'spreadsheetMode': 'Электронная таблица',
  'drawingMode': 'Рисование',
  'calculatorMode': 'Калькулятор',
  'symbolsMode': 'Символы',
  'latexMode': 'LaTeX',
  'documentSaved': 'Документ успешно сохранен',
  'errorOccurred': 'Произошла ошибка',
};
